### ISSUE TITLE
Nginx not reloading with many services starting up together

### ISSUE THREAD

**Issue by thefosk** [joyent/containerpilot#216]
Sometimes when there are many services starting up and registering themselves to Consul at the same time (like 6/7 services), it seems like Nginx doesn't properly reload to regenerate the configuration every time, and I need to manually trigger a `docker restart CONTAINER_ID` in order to force Nginx to re-generate the correct configuration after all the services are finally up and running.

Is anybody else dealing with this issue?

**Comment by fitz123** [comment]
What is your configuration?
Are you using "Backend" or directly consul-template for templates generation? These multiple services are in same container or not?
Please share details. I have configuration with dozens of servers and all templates are fine, nginx restarts correctly

**Comment by thefosk** [comment]
I have the following Docker Compose configuration for Consul/Nginx:

```yaml
nginx-lb:
  build: nginx/
  mem_limit: 128m
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 3001:3001
    - 10000:10000
    - 10001:10001
    - 10002:10002
    - 10003:10003
  expose:
    - 8000
    - 8443
    - 8001
    - 3001
    - 10000
    - 10001
    - 10002
    - 10003
  links:
    - consul:consul
  restart: always
  command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"

consul:
  image: progrium/consul:latest
  command: -server -bootstrap -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
  dns:
    - 127.0.0.1

# All the services definitions are below here
# ....
```

And each service has a `containerpilot.json` similar to:

```
{
  "consul": "consul:8500",
  "services": [
    {
      "name": "hello-world",
      "port": 8080,
      "health": "/usr/bin/curl -s -o /dev/null http://localhost:8080/",
      "poll": 3,
      "ttl": 10
    }
  ]
}
```

## Nginx

The Nginx server has the following `containerpilot.json` configuration:

```json
{
  "consul": "consul:8500",
  "preStart": "/bin/reload-nginx.sh preStart",
  "logging": {
    "level": "DEBUG",
    "format": "text"
  },
  "services": [
    {
      "name": "nginx",
      "port": 80,
      "interfaces": ["eth1", "eth0"],
      "health": "/usr/bin/curl -o /dev/null --fail -s http://localhost/health",
      "poll": 10,
      "ttl": 25
    }
  ],
  "backends": [
    {
      "name": "service-8000",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service-8443",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service-8001",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service1",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service2",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service3",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    }
  ]
}
```

The following `nginx.conf.ctmpl` template:

```nginx
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 65536;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    charset UTF-8;

    server {
        listen 80;
        location /health {
            # requires http_stub_status_module
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
}

stream {
    {{range services}}
    upstream {{.Name}} {
        least_conn;{{range service .Name}}
        server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;{{else}}
        server 0.0.0.1:80; # invalid placeholder{{end}}
    }{{range $index, $element := service .Name}}{{if eq $index 0}}
    server {
        listen {{.Port}};
        proxy_pass {{.Name}};
    }
    {{end}}{{end}}{{end}}
}
```

and the following `reload-nginx.sh` script:

```shell
#!/bin/sh

# Render Nginx configuration template using values from Consul,
# but do not reload because Nginx has't started yet
preStart() {
    consul-template \
        -once \
        -consul consul:8500 \
        -template "/etc/containerpilot/nginx.conf.ctmpl:/etc/nginx/nginx.conf"
}

# Render Nginx configuration template using values from Consul,
# then gracefully reload Nginx
onChange() {
    consul-template \
        -once \
        -consul consul:8500 \
        -template "/etc/containerpilot/nginx.conf.ctmpl:/etc/nginx/nginx.conf:nginx -s reload"
}

until
    cmd=$1
    if [ -z "$cmd" ]; then
        onChange
    fi
    shift 1
    $cmd "$@"
    [ "$?" -ne 127 ]
do
    onChange
    exit
done
```
