### ISSUE TITLE
Defunct process when containerpilot kills a timedout task

### ISSUE THREAD

**Issue by roengram** [joyent/containerpilot#447]
I thought this was solved by #409 but I observed similar behaviour in a slightly different setting.
I used containerpilot 2.7.6 and let containerpilot periodically executes a script with 1 sec timeout.
The script executes *curl* to get from 1.2.3.4/index.htm, which makes curl hang more than 1sec. containerpilot kills it for timeout, and the curl process becomes defunct after waking up from hang.
I'm not sure if this is containerpilot issue. This may be because of the way I made the recurring script.

Please find an attachement for reproduction. Just ignore the misleading name of "sleeper". It's actually "curl-er".
[containerpilot.tar.gz](https://github.com/joyent/containerpilot/files/1178869/containerpilot.tar.gz)

**Comment by tgross** [comment]
docker-compose.yml

```yml
version: '2'
services:
    consul:
        image: consul:0.9.0
        container_name: consul

    sleeper:
        build: ./sleeper
        container_name: sleeper
        links:
         - consul
        command: /bin/containerpilot -config file:///containerpilot.json sleep 3600
```

Dockerfile:
```
FROM centos:centos7

RUN export CP_SHA1=4c811736eb66db9535b1bded531d225041ed1da3 \ 
    && curl -Lso /tmp/containerpilot.tar.gz "https://github.com/joyent/containerpilot/releases/download/2.7.6/containerpilot-2.7.6.tar.gz" \
    && echo "${CP_SHA1} /tmp/containerpilot.tar.gz" | sha1sum -c \
    && tar zxf /tmp/containerpilot.tar.gz -C /bin \
    && rm /tmp/containerpilot.tar.gz
ADD containerpilot.json /containerpilot.json 
ADD sleep.sh /sleep.sh
```

ContainerPilot config:

```json
{
  "consul": "consul:8500",
  "logging": {
    "level": "DEBUG",
    "format": "default",
    "output": "stdout"
  },
  "services": [
    {
      "name": "sleeper",
      "port": 8080,
      "poll": 10,
      "ttl": 30
    }
  ],
  "tasks": [
    {
      "name": "sleep1s",
      "command": ["sh", "/sleep.sh", "2"],
      "frequency": "3000ms",
      "timeout": "1000ms"
    }
  ]
}
```

sleep.sh:

```sh
#!/bin/bash

curl -m 2 -s 1.2.3.4/index.htm
```
