### ISSUE TITLE
Two containerpilot processes running (2.7.7)

### ISSUE THREAD

**Issue by roengram** [joyent/containerpilot#463]
Hi. I tried containerpilot 2.7.7.
Certainly I don't see defunct processes any more, but there are two containerpilot processes running inside the container:
```
roengram@containerpilot$ docker exec -it sleeper ps -aef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 02:22 ?        00:00:00 /bin/containerpilot -config file
root        12     1  0 02:22 ?        00:00:00 /bin/containerpilot -config file
root        19    12  0 02:22 ?        00:00:00 sleep 3600
root        36     0  0 02:22 ?        00:00:00 ps -aef

roengram@containerpilot$ docker exec -it sleeper /bin/containerpilot -version
Version: '2.7.7'
GitHash: 'c2e2525'
```

Below are the files to reproduce the above:

docker-compose.yml:
```
version: '2' 
services:
    consul:
        image: consul:0.9.0
        container_name: consul

    sleeper:
        build: ./sleeper
        container_name: sleeper
        links:
         - consul
        command: /bin/containerpilot -config file:///containerpilot.json sleep 3600
```

sleeper/Dockerfile:
```
FROM centos:centos7

RUN export CP_SHA1=030f1e54a43a842d38b30373f8847132a9771829 \ 
    && curl -Lso /tmp/containerpilot.tar.gz "https://github.com/joyent/containerpilot/releases/download/2.7.7/containerpilot-2.7.7.tar.gz" \
    && echo "${CP_SHA1} /tmp/containerpilot.tar.gz" | sha1sum -c \
    && tar zxf /tmp/containerpilot.tar.gz -C /bin \
    && rm /tmp/containerpilot.tar.gz
ADD containerpilot.json /containerpilot.json 
ADD sleep.sh /sleep.sh
```

sleeper/containerpilot.json:
```
{
  "consul": "consul:8500",
  "logging": {
    "level": "DEBUG",
    "format": "default",
    "output": "stdout"
  },  
  "services": [
    {   
      "name": "sleeper",
      "port": 8080,
      "poll": 10, 
      "ttl": 30
    }   
  ],  
  "tasks": [
    {   
      "name": "sleep1s",
      "command": ["sh", "/sleep.sh", "2"],
      "frequency": "3000ms",
      "timeout": "1000ms"
    }   
  ]
}
```

sleeper/sleeper.sh:
```
#!/bin/bash

curl -m 2 -s 1.2.3.4/index.htm
```
